Adds Sparkline types
britecharts/britecharts-typings pull request #20
Opened 2020-09-23 04:48 UTC by Golodhros

## Description

Adds the Sparkline Types
Starts a more granular set of interfaces

## Motivation and Context

Completing the project

## How Has This Been Tested?

Manually on the sandbox

## Screenshots (if appropriate):
![Britecharts_test_for_typescript_](https://user-images.githubusercontent.com/190833/93968022-621a6f80-fd1d-11ea-89f5-d85c128939de.png)

## Types of changes

- [ ] Refactor (changes the way we code something without changing its functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Latest master code has been merged into this branch
- [ ] No commented out code (if required, place // TODO above with explanation)
- [ ] No linting issues
- [ ] Build is successful
- [ ] Updated the documentation
- [ ] Added tests to cover changes
- [ ] All new and existing tests passed

2020-09-23 04:50 UTC, Golodhros commented on src/typings/charts/sparkline-chart.d.ts
> +  titleTextStyle(titleStyle?: any): SparklineChartModule;
No idea of how to type this!

2020-09-23 07:09 UTC, DalerAsrorov requested changes

2020-09-23 07:09 UTC, DalerAsrorov commented on src/typings/charts/sparkline-chart.d.ts
> +  titleTextStyle(titleStyle?: any): SparklineChartModule;
I would create a new interface for this in the same file:
```js
export interface SparkelineTitleTextStyle {
  'font-family'?: string;
  'font-size'?: string,
  'font-weight'?: number,
  'font-style'?: string,
  'fill'?: string,
}
```
and then apply it:
```js
 titleTextStyle(titleStyle?: SparkelineTitleTextStyle): SparklineChartModule;
```
These are the only CSS attributes that are being set optionally anyway:
https://github.com/britecharts/britecharts/blob/f2df886c2ea25c33f1a94cbd86d17dbe7c23b392/src/charts/sparkline.js#L350-L354

2020-09-24 01:00 UTC, DalerAsrorov approved these changes

2020-09-24 01:00 UTC, merged