feat: Adds Tooltip types
britecharts/britecharts-typings pull request #26
Opened 2020-10-21 05:14 UTC by Golodhros

## Description

Adds the tooltip types

NOTE: There is a bug somewhere as the tooltip only shows properly on the first item, but I couldn't figure out what's the problem.

## Motivation and Context
Completing our types

## How Has This Been Tested?
Manually on sandbox

## Types of changes

- [ ] Refactor (changes the way we code something without changing its functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Latest master code has been merged into this branch
- [ ] No commented out code (if required, place // TODO above with explanation)
- [ ] No linting issues
- [ ] Build is successful
- [ ] Updated the documentation
- [ ] Added tests to cover changes
- [ ] All new and existing tests passed

2020-10-21 15:22 UTC, DalerAsrorov requested changes
A few minor comments but looks good otherwise!

2020-10-21 15:22 UTC, DalerAsrorov commented on src/sandbox/tooltip.ts
> +export const constructChart = (containerNode: Element): {lineChartWithTooltip: LineChartModule, tooltipComponent:any} => {
Is any the best usage scenario here?

2020-10-21 15:22 UTC, DalerAsrorov commented on src/typings/charts/tooltip.d.ts
> +type FormattingFunction = (value: number) => number;
Seems like there is no need to create a separate declaration for this, can directly use the (value:number) => number

2020-10-21 20:16 UTC, Golodhros commented on src/sandbox/tooltip.ts
> +export const constructChart = (containerNode: Element): {lineChartWithTooltip: LineChartModule, tooltipComponent:any} => {
True, I will use TooltipModule instead

2020-10-21 20:17 UTC, Golodhros commented on src/typings/charts/tooltip.d.ts
> +type FormattingFunction = (value: number) => number;
I think it looks more tidy this way, but next time I will leave it in place

2020-10-22 15:26 UTC, DalerAsrorov approved these changes

2020-10-22 15:26 UTC, merged